# Generated by Django 4.0.5 on 2022-07-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='warehouse',
            field=models.CharField(max_length=200),
        ),
    ]
