# Generated by Django 4.0.5 on 2022-07-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_shipping_comment_alter_shipping_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='district',
        ),
    ]
