# Generated by Django 4.0.5 on 2022-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обробці', 'В обробці'), ('Відправлено', 'Відправлено'), ('Скасовано', 'Скасовано'), ('Доставлено', 'Доставлено')], default='В обробці', max_length=200),
        ),
    ]
